RANDOM_WELCUM = [
    f"Welcome, {mention}! 🌟 Your journey in {member.chat.title} begins now.",
    f"Glad to have you here, {mention}! 🎉 {member.chat.title} just got better.",
    f"A warm welcome to {mention}! 🌈 Get ready for the magic of {member.chat.title}.",
    f"Hello, {mention}! 🌟 Joining {member.chat.title} is the best decision you've made.",
    f"Welcome aboard, {mention}! 🚀 {member.chat.title} is now your adventure zone.",
    f"{mention}, welcome to {member.chat.title}! 🌺 Embrace the warmth of our community.",
    f"A big hello to {mention}! 🌈 Your presence brightens up {member.chat.title}.",
    f"Cheers, {mention}! 🎊 {member.chat.title} just gained an awesome member.",
    f"{mention}, welcome to the family of {member.chat.title}! 🚀 Exciting times ahead.",
    f"Hi there, {mention}! 🌟 Ready to create wonderful memories in {member.chat.title}?",
    f"{mention}, a warm welcome to {member.chat.title}! 🌈 Let the journey begin.",
    f"Greetings, {mention}! 🎉 {member.chat.title} is now enriched with your presence.",
    f"Welcome, {mention}! 🚀 {member.chat.title} is now your home away from home.",
    f"{mention}, thrilled to have you join {member.chat.title}! 🌟",
    f"Hi, {mention}! 🌈 Get ready for an amazing experience in {member.chat.title}.",
    f"A hearty welcome to {mention}! 🎊 {member.chat.title} is lucky to have you.",
    f"{mention}, welcome to the fantastic world of {member.chat.title}! 🚀",
    f"Cheers to {mention}! 🌟 {member.chat.title} just got a whole lot better.",
    f"Hello, {mention}! 🌈 Your presence adds magic to {member.chat.title}.",
    f"Welcome aboard, {mention}! 🎉 {member.chat.title} is now complete with you.",
    f"{mention}, a warm welcome to the family of {member.chat.title}! 🌟",
    f"Glad you're here, {mention}! 🚀 {member.chat.title} awaits your adventures.",
    f"Hi, {mention}! 🌈 {member.chat.title} is now brighter with your arrival.",
    f"{mention}, welcome to {member.chat.title}! 🎊 Your journey begins now.",
    f"Welcome, {mention}! 🌟 {member.chat.title} is thrilled to have you join us.",
    f"{mention}, a big hello from {member.chat.title}! 🚀 Get ready for fun times.",
    f"Greetings, {mention}! 🌈 {member.chat.title} just became more exciting with you.",
    f"A warm welcome to {mention}! 🎉 {member.chat.title} celebrates your arrival.",
    f"Cheers, {mention}! 🌟 {member.chat.title} is now your playground.",
    f"Hello, {mention}! 🌈 Your journey in {member.chat.title} starts now!",
    f"{mention}, welcome to the family of {member.chat.title}! 🚀",
    f"Thrilled to have you here, {mention}! 🌟 {member.chat.title} is now complete.",
    f"Hi, {mention}! 🌈 {member.chat.title} welcomes you with open arms.",
    f"{mention}, a warm welcome to {member.chat.title}! 🎊 Let the adventure begin.",
    f"Welcome, {mention}! 🌟 {member.chat.title} is now brighter with you in it.",
    f"{mention}, glad you're here! 🚀 {member.chat.title} is now your second home.",
    f"A big hello to {mention}! 🌈 {member.chat.title} is ready for your story.",
    f"Cheers, {mention}! 🌟 {member.chat.title} is now enriched with your presence.",
    f"{mention}, welcome to the fantastic world of {member.chat.title}! 🎉",
    f"Glad to have you here, {mention}! 🚀 {member.chat.title} awaits your magic.",
    f"Hi, {mention}! 🌈 Your journey in {member.chat.title} begins now.",
    f"{mention}, a warm welcome to the family of {member.chat.title}! 🌟",
    f"Thrilled to have you here, {mention}! 🎊 {member.chat.title} just got better.",
    f"Hello, {mention}! 🚀 {member.chat.title} is now complete with your arrival.",
    f"Welcome, {mention}! 🌈 {member.chat.title} is now your adventure zone.",
    f"{mention}, welcome to the fantastic world of {member.chat.title}! 🌟",
    f"A big hello to {mention}! 🎉 {member.chat.title} celebrates your arrival.",
    f"Cheers, {mention}! 🚀 {member.chat.title} is now enriched with your presence.",
    f"Glad you're here, {mention}! 🌈 {member.chat.title} awaits your adventures.",
    f"Hi, {mention}! 🌟 {member.chat.title} is thrilled to have you join us.",
    f"{mention}, a warm welcome to {member.chat.title}! 🎊 Your journey begins now.",
    f"Thrilled to have you here, {mention}! 🌈 {member.chat.title} just got a whole lot better.",
    f"Welcome, {mention}! 🚀 {member.chat.title} is now brighter with you in it.",
    f"{mention}, glad you're here! 🌟 {member.chat.title} is now your second home.",
    f"A big hello to {mention}! 🌈 {member.chat.title} is ready for your story.",
    f"Cheers, {mention}! 🎉 {member.chat.title} is now enriched with your presence.",
    f"{mention}, welcome to the family of {member.chat.title}! 🚀 Let the adventure begin.",
    f"Glad to have you here, {mention}! 🌟 {member.chat.title} awaits your magic.",
    f"Hi, {mention}! 🌈 Your journey in {member.chat.title} begins now.",
    f"{mention}, a warm welcome to the family of {member.chat.title}! 🌟",
    f"Thrilled to have you here, {mention}! 🎊 {member.chat.title} just got better.",
    f"Hello, {mention}! 🚀 {member.chat.title} is now complete with your arrival.",
    f"Welcome, {mention}! 🌈 {member.chat.title} is now your adventure zone.",
    f"{mention}, welcome to the fantastic world of {member.chat.title}! 🌟",
    f"A big hello to {mention}! 🎉",
]
