import io
import os

import requests
from PIL import Image
from pyrogram import filters
from pyrogram.types import InlineKeyboardButton, InlineKeyboardMarkup, Message

from MissCutie import SUPPORT_CHAT, dispatcher, pbot


def get_text(message: Message) -> [None, str]:
    text_to_return = message.text
    if message.text is None:
        return None
    if " " in text_to_return:
        try:
            return message.text.split(None, 1)[1]
        except IndexError:
            return None
    else:
        return None


@pbot.on_message(filters.command(["wall", "wallpaper"]))
async def wall(client, message):
    quew = get_text(message)
    if not quew:
        await client.send_message(
            message.chat.id, "😶 **please give some text to search for wallpaper !**"
        )
        return
    m = await client.send_message(message.chat.id, "⚙️ **searching for wallpaper...**")
    try:
        text = get_text(message)
        LOGO_API = f"https://single-developers.up.railway.app/wallpaper?search={text}"
        randc = LOGO_API
        murl = (
            requests.get(
                f"https://single-developers.up.railway.app/wallpaper?search={text}"
            )
            .history[1]
            .url
        )
        img = Image.open(io.BytesIO(requests.get(randc).content))
        fname = "MissCutie.png"
        img.save(fname, "png")
        caption = f"""
💘 wallpaper generated successfully 

✨ **generated By :** [{dispatcher.bot.first_name}](https://t.me/{dispatcher.bot.username})
🥀 **reǫuested By :** {message.from_user.mention}
❄ **download :** `{murl}`
"""
        await m.delete()
        await client.send_photo(
            message.chat.id,
            photo=murl,
            caption=caption,
            reply_markup=InlineKeyboardMarkup(
                [
                    [InlineKeyboardButton("• link •", url=f"{murl}")],
                ]
            ),
        )
        if os.path.exists(fname):
            os.remove(fname)
    except Exception as e:
        await client.send_message(
            message.chat.id,
            f"something went wrong.\nplease report this at @{SUPPORT_CHAT}\n\n**error :** {e}",
        )
